"""
Script to visualize soccer events from JSON files.

This script reads event data from JSON files generated by the make_json.py script
and displays the event labels, teams, and visibility in a simple plot.
"""

import json
import os
import argparse
import matplotlib.pyplot as plt


def parse_arguments():
    """
    Parse command line arguments.

    Returns:
        argparse.Namespace: Parsed command line arguments containing match_id.
    """
    parser = argparse.ArgumentParser(description="Visualize soccer events from JSON files")
    parser.add_argument("--match_id", required=True, help="Match ID to visualize events for")
    parser.add_argument(
        "--data_path", default="/home/atom/SoccerTrack-v2/data/raw", help="Path to the raw data directory"
    )
    return parser.parse_args()


def visualize_events(match_id: str, data_path: str) -> None:
    """
    Visualize events from the JSON file for a specific match.

    Args:
        match_id (str): ID of the match to visualize.
        data_path (str): Base path to the raw data directory.
    """
    json_file_path = os.path.join(data_path, match_id, f"{match_id}_12_class_events.json")  # Adjust class as needed

    if not os.path.exists(json_file_path):
        print(f"JSON file not found: {json_file_path}")
        return

    with open(json_file_path, "r") as json_file:
        event_data = json.load(json_file)

    # Extract event details
    annotations = event_data.get("annotations", [])
    labels = [annotation["label"] for annotation in annotations]
    teams = [annotation["team"] for annotation in annotations]
    visibility = [annotation["visibility"] for annotation in annotations]

    # Create a simple plot
    plt.figure(figsize=(10, 6))
    plt.title(f"Events for Match ID: {match_id}")
    plt.xlabel("Event Index")
    plt.ylabel("Event Details")

    for i, (label, team, vis) in enumerate(zip(labels, teams, visibility)):
        event_detail = f"Label: {label}, Team: {team}, Visibility: {vis if vis else 'N/A'}"
        plt.text(i, 0, event_detail, fontsize=10, ha="left", va="center")

    plt.yticks([])  # Hide y-axis ticks
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    args = parse_arguments()
    visualize_events(args.match_id, args.data_path)
